config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root controller: :public, action: :index

  resources :room_messages
  resources :rooms

  # Redirect to landing page if the route isn't found
  match "*path" => redirect{|path, request| request.flash[:error] = "The page you tried to access doesn't exist."; "/"}, via: [:post, :get, :put, :patch, :delete], constraints: lambda { |req|
    # Allow active storage requests
    req.path.exclude? 'rails/active_storage'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room

  # Order by latest message. If a room has no messages it will be put at the end.
  scope :order_latest, -> { includes(:room_messages).order('room_messages.created_at DESC NULLS LAST') }
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord

  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  # Require minimum 1 character to validate a message
  validates :message, length: {minimum: 1}, allow_blank: false
  # Don't allow only whitespace in a message
  validates :message, format: {with: /.*\S.*/}

  # Add avatar URI and username to the JSON representation of a message
  def as_json(options)
    avatar = "/assets/default-avatar.png"
    if user.avatar.present?
      avatar = Rails.application.routes.url_helpers.rails_representation_url(user.avatar.variant(resize_to_limit: [128, 128]).processed, only_path: true)
    end
    super(options).merge(username: user.username, user_avatar_url: avatar)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true

  has_one_attached :avatar

  validates :avatar, file_size: { less_than_or_equal_to: 5.megabytes },
            file_content_type: { allow: ["image/jpeg", "image/png", "image/gif"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :initialize_active_storage

  # Redirect user to list of chat rooms on log in
  def after_sign_in_path_for(user)
    rooms_path
  end

  protected

  # Allow extra properties to be set on Devise user model at sign up
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end

  def initialize_active_storage
    # ActiveStorage::Current.host = request.base_url
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  # Displays the homepage/landing page
  def index
    if user_signed_in?
      redirect_to rooms_path 
    else
      render
    end
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  
  before_action :authenticate_user!

  before_action :load_entities

  def create
    @room_message = RoomMessage.create user: current_user, room: @room, message: params.dig(:room_message, :message)

    RoomChannel.broadcast_to @room, @room_message if @room_message.valid?
  end

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  before_action :load_entities

  def index
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.order(created_at: :asc).includes(:user).last(50)
  end

  protected

  def load_entities
    @rooms = Room.order_latest
    @room = Room.find(params[:id]) if params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChitChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/header" %>

    <div class="container flex-grow-1 flex-shrink-1 d-flex flex-column">
      
      <div class="row">
        <div class="col-12">
          <%= render partial: "shared/flash_messages" %>
        </div>
      </div>

      <div class="row flex-grow-1 flex-shrink-1">
        <div class="col-12 d-flex flex-column">
          <%= yield %>
        </div>
      </div>
      
    </div>
    
  </body>
</html>

app/views/rooms/index.html.erb
<% if @rooms.present? %>
  <div class="mb-3 d-flex justify-content-between align-items-center">
    <h3 class="mb-0">Chatrooms</h3>
    <%= link_to "Reload", request.url, class: "btn btn-primary" %>
  </div>
  <div class="room-list rounded overflow-hidden border border-dark">
    <% @rooms.each do |room| %>
      <%= link_to room_path(room), class: "room-list-item" do %>
        <div class="p-2 d-flex">
          <i class="fa-solid fa-chevron-right d-flex align-items-center pr-2"></i>
          <div>
            <p class="mb-0 h5"><%= room.name %></p>
            <p class="mb-0"><%= room.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <p class="text-muted">There are currently no chatrooms available.</p>
<% end %>

app/views/rooms/show.html.erb
<div class="chat-wrapper flex-grow-1 flex-shrink-1">
  <div class="chat">
    <div class="messages px-3" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
    
      <% @room_messages.each do |room_message| %>

        <div class="chat-message-container d-flex py-2">
          <div class="avatar-container mr-2 rounded-circle overflow-hidden d-flex align-items-center justify-content-center bg-dark">
            <img src="<%= room_message.user.avatar.present? ? rails_representation_url(room_message.user.avatar.variant(resize_to_limit: [128, 128]).processed, only_path: true) : "/assets/default-avatar.png" %>" data-role="user-avatar" class="img-fluid">
          </div>

          <div class="chat-message-content">
            <p class="mb-0">
              <span class="username font-weight-bold"><%= room_message.user.username %></span>
              <small class="timestamp text-muted"><%= room_message.created_at %></small>
            </p>
            <p class="mb-0"><%= room_message.message %></p>
          </div>
        </div>

      <% end %>
    
    </div>
  </div>
</div>

<%= simple_form_for @room_message, remote: true do |form| %>
  <div class="input-group mb-3">
    <%= form.input :message, as: :string, 
                              wrapper: false, 
                              label: false, 
                              input_html: { 
                                class: "chat-input",
                                autocomplete: "off"
                              } %>
    
    <div class="input-group-append">
      <%= form.submit "Send", class: "btn btn-primary chat-input" %>
    </div>
  </div>

  <%= form.input :room_id, as: :hidden %>
<% end %>


<div class="d-none" data-role="message-template">
  <div class="chat-message-container d-flex py-2">
    <div class="avatar-container mr-2 rounded-circle overflow-hidden d-flex align-items-center justify-content-center bg-dark">
      <img src="/assets/default-avatar.png" data-role="user-avatar" class="img-fluid">
    </div>

    <div class="chat-message-content">
      <p class="mb-0">
        <span class="username font-weight-bold" data-role="message-username"></span>
        <small class="date text-muted" data-role="message-date"></small>
      </p>
      <p class="mb-0 message-text" data-role="message-text"></p>
    </div>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-info">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="main-header bg-dark">
  <div class="container">
    <div class="row w-100">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark w-100 justify-content-between">
        <a href="<%= root_path %>" class="navbar-brand">Chit<span class="text-primary">Chat</span></a>
        <% if current_user %>
          <div class="d-flex align-items-center">
            <%= link_to "Browse", rooms_path, class: "btn btn-primary mr-3" %>

            <div class="dropdown">
              <a class="nav-link dropdown-toggle d-flex align-items-center p-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="avatar-container mr-2 rounded-circle overflow-hidden d-flex align-items-center justify-content-center bg-secondary">
                  <img src="<%= current_user.avatar.present? ? rails_representation_url(current_user.avatar.variant(resize_to_limit: [128, 128]).processed, only_path: true) : "/assets/default-avatar.png" %>" data-role="user-avatar" class="img-fluid">
                </div>
                <%= current_user.username %>
              </a>


              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </div>
            </div>
          </div>
        <% end %>
      </nav>
    </div>
  </div>
</header>